layout_spectrum: 0.6702509
color:
  saturation: 1
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#F8E7DD'
    - '#EDD5C9'
    - '#F1DCCB'
    - '#C8B9B2'
    - '#FFEEE7'
  rhythmicContrast: 1
typography_spectrum: 0.5788531
name: rogue girl gone fashion
